{ config, pkgs, ... }:
{
  xdg.configFile."workstyle/config.toml".text = ''
    "github" = ""
    "rust" = ""
    "google" = ""
    "private browsing" = ""
    "librewolf" = ""
    "nvim" = ""
    "gthumb" = ""
    ".pdf" = ""
    "foot-notes" = ""
    "yazi" = "󰇥"
    "tmux" = ""
    "obsidian" = " "
    "youtube music" = ""
    "brave" = ""
    "vesktop" = ""
    "vlc" = "󰕼"
    "youtube" = ""
    "qutebrowser" = ""
    "reddit" = ""
    "twitch" = ""
    "twitter" = ""
    "x.com" = ""
    "spotify" = ""
    "netflix" = "󰝆"
    "amazon" = ""
    "steam" = ""
    "discord" = "󰙯"
    "slack" = ""
    "signal" = "󰈹"
    "telegram" = ""
    "whatsapp" = ""
    "zoom" = ""
    "notion" = "󰎚"
    "trello" = ""
    "figma" = ""
    "bitbucket" = ""
    "gitlab" = ""
    "stackoverflow" = ""
    "duckduckgo" = "󰇥"
    "wikipedia" = ""
    "chatgpt" = "󰚩"
    "outlook" = ""
    "gmail" = ""
    "calendar" = ""
    "keep" = ""
    "drive" = ""
    "dropbox" = ""
    "ssh" = ""

    [other]
    fallback_icon = ""
    deduplicate_icons = false
    separator = ": "
  '';
}
